[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names and functions
file_template = %%(rev)s_%%(slug)s

# timezone aware timestamps
# Ensure migrations are timezone aware
# version_location = head

# encoding for script files
# file_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://certiflow:certiflow@localhost:5432/certiflow